
#include <bits/stdc++.h>
using namespace std;

#define PB push_back
#define F first
#define S second
#define MP make_pair
#define LL long long
#define ppl pair<LL, LL>

int main()
{
    static const int _ = []() {
        ios::sync_with_stdio(false);
        cin.tie(NULL);
        cout.tie(NULL);
        return 0;
    }();

    int t, s;
    cin >> t >> s;
    while (t--)
    {
        LL n;
        cin >> n;
    }
    return 0;
}
